trigger:
- main
pool:
    vmImage: ubuntu-latest
variables:
    buildConfiguration: 'Release'

steps:
    - script: ls
       dotnet build --configuration $(buildConfiguration)
       displayName:'dotnet build $(buildConfiguration)'


